Repository processone/tsung, pull requests merged in 2018-06, with the labels that each got.

#292 Make generated graphs more comparable over time and space.
  src/tsung_stats.pl.in
Labels: area/reporting, kind/enhancement

#296 Add custom headers with websocket request
  docs/conf-sessions.rst
  include/ts_websocket.hrl
  src/lib/websocket.erl
  src/test/ts_test_websocket.erl
  src/tsung/ts_websocket.erl
  src/tsung_controller/ts_config_http.erl
  src/tsung_controller/ts_config_websocket.erl
  tsung-1.0.dtd
Labels: kind/feature, protocol/http, protocol/websockets

#258 tsung fails in ts_dynvars:merge when arguments are [<<>>, Dynvars]
  src/tsung/ts_dynvars.erl
Labels: kind/bug

#265 use debian compatibility level 9 for 'make deb'
  debian/compat
  debian/rules
Labels: kind/enhancement

#273 Mqtt connect's will topic with dynamic substitution
  src/tsung/ts_mqtt.erl
Labels: protocol/mqtt

#310 Fix connection with websocket ssl
  src/tsung/ts_server_websocket_ssl.erl
Labels: kind/bug, protocol/websockets
